### ISSUE TITLE
Allow auto-completion in the `atlas.config.json` file.

### ISSUE THREAD

**Issue by PhaserEditor2D** [ourcade/vscode-texture-packer#2]
Allow auto-completion of the `atlas.config.json` parameters. Maybe using a [json schema](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings).

**Comment by supertommy** [comment]
I like this too; haven't used json schema before so I'll have to do some research!

**Comment by PhaserEditor2D** [comment]
💪

**Comment by supertommy** [comment]
Added in `v0.0.6` and I used https://github.com/YousefED/typescript-json-schema to autogenerate it from the type declaration

**Comment by PhaserEditor2D** [comment]
👏
